# Generated by Django 3.2.8 on 2021-10-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avisos_normas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avisos',
            new_name='Aviso',
        ),
        migrations.RenameModel(
            old_name='Normas',
            new_name='Norma',
        ),
    ]
