# Generated by Django 3.2.8 on 2021-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_aviso_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='norma',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
