# Generated by Django 3.2.8 on 2021-10-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_norma_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma',
            name='tags',
        ),
    ]
