# Generated by Django 3.2.8 on 2021-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_norma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('origem', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_validade', models.DateTimeField(null=True)),
            ],
        ),
    ]
