# Generated by Django 3.2.8 on 2021-10-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_norma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
