# Generated by Django 3.2.8 on 2021-10-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211025_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='norma',
            name='data_validade',
        ),
    ]
