# Generated by Django 3.2.8 on 2021-10-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211025_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Norma',
        ),
    ]
