# Generated by Django 3.2.8 on 2021-10-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
