# Generated by Django 3.2.8 on 2021-10-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_aviso_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
    ]
